# Generated by Django 3.0.5 on 2020-04-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_food',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet_food',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet_food',
            name='pet',
            field=models.CharField(max_length=10),
        ),
    ]
